name: Publish to npm

on:
  # 手动触发
  workflow_dispatch:
  push:
    branches:
      - main # 触发分支，根据需要替换

jobs:
  publish:
    runs-on: ubuntu-latest
    # 关键修改：判断是手动触发 或 提交信息包含[publish]
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[publish]')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Set the Node.js version you're using (e.g., 16 or 18)

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish
